name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - name: Backup our files
        run: |
          cp lib/main.dart /tmp/main.dart
          cp pubspec.yaml /tmp/pubspec.yaml
      - name: Create Android project
        run: flutter create --platforms=android .
      - name: Restore our app code
        run: |
          cp /tmp/main.dart lib/main.dart
          cp /tmp/pubspec.yaml pubspec.yaml
      - run: flutter pub get
      - run: flutter build apk --release --no-tree-shake-icons
      - uses: actions/upload-artifact@v4
        with:
          name: MarketMakerAI-apk
          path: build/app/outputs/flutter-apk/app-release.apk
